name: HubCore
main: HubCore\HubCore
version: 1.2.2
api: 3.14.0
author: IceCruelStuff
description: Adds /hub command to your PocketMine-MP server
website: https://github.com/IceCruelStuff/HubCore

commands:
  hub:
    description: Teleport to hub
    usage: "/hub"
    permission: hub.command

  lobby:
    description: Teleport to lobby
    usage: "/lobby"
    permission: hub.command

  spawn:
    description: Teleport to spawn
    usage: "/spawn"
    permission: hub.command

  sethub:
    description: Set the hub
    usage: "/sethub"
    permission: hub.set

  setlobby:
    description: Set the lobby
    usage: "/setlobby"
    permission: hub.set

  setspawn:
    description: Set the spawn
    usage: "/setspawn"
    permission: hub.set

permissions:
  hub.command:
    description: Allows you to teleport to hub
    default: true

  hub.set:
    description: Allows you to set the hub
    default: op
