name: HubCore
main: HubCore\HubCore
version: 1.3
api: 3.15.0
author: IceCruelStuff
description: Adds /hub command to your PocketMine-MP server
website: https://github.com/IceCruelStuff/HubCore

permissions:
  hub.command:
    description: Allows you to teleport to hub
    default: true

  hub.set:
    description: Allows you to set the hub
    default: op
